paulrosen/abcjs

api/abc_animation.js

In `ABCJS.startAnimation()`, the `makeSortedArray()` function sorts the event hash by time, but it doesn't account for the scenario where a note can precede a bar with the same time value in the original unsorted array. In this scenario, because the time difference is 0, the note will precede the bar, which causes problems for the animation (in my experience, ABCJS believes the measure before the bar to contain an extra note which should actually be in the measure after the bar). To solve this, I've added a few lines to check whether the time difference is 0, and if it is, to make sure the bar comes first. This should address #27.

Correct order of timing events for animation

---

parse/abc_parse.js

According to http://abcnotation.com/wiki/abc:standard:v2.1#mmeter
> When there is no M: field defined, free meter is assumed

If no meter is specified, free meter is assumed

---

parse/abc_parse_header.js

For example :
````
M: 4/4
C8 | [M: 2/4] C8
````
Both Cs should have a length of 1. Because according to http://abcnotation.com/wiki/abc:standard:v2.1#lunit_note_length
>If there is no L: field defined, a unit note length is set by default, based on the meter field M:. (...)
>**A meter change within the body of the tune will not change the unit note length**.

Do not change the default note length when meter is change inline

---

parse/abc_parse_header.js

According to http://abcnotation.com/wiki/abc:standard:v2.1#lunit_note_length
> L:1 (whole note) (...) are also available

L: 1 (whole note) should be accepted as note length

---

parse/abc_parse.js

HI Paul, I have implemented issue #14 as far as I was able to. It boils down to a new method in ABCJS.parser.getWarningObjects which yields an array of objects
{
message:str,       // the error message 
line:line,              // the broken line
startChar: multilineVars.iChar + col_num, // the startChar of the error
column: col_num  // the position of the error within line
}
Based on this, i was able to highlight the error position in my editor.
As this API does not break backwards compatibility at all, I kindly ask you to incorporate it.

provide access to warnings as objects (see issue #14)

---

src/midi/abc_midi_controls.js

This allows MIDI download link styling using an arbitrary class name. Especially useful for adopting classes provided by a CSS framework, and so using consistent class names across the site.

Add custom class to generated MIDI download div

---

src/api/abc_timing_callbacks.js

If `extraMeasuresAtBeginning` is not set in param make it 0 as in the API documentation.

Make extraMeasuresAtBeginning default to 0

---

abcjs-midi.css
midi.js
src/midi/abc_midi_controls.js

These 2 commits add 2 different functionality:
4c043a7: Move the indicator in the correct position after clicking on the progress bar
53e4e00: Allow users to drag the indicator along the progress bar

New functionalities around progress bar 

---

src/midi/abc_midi_controls.js

As posted here: https://github.com/paulrosen/abcjs/commit/53e4e009dfb3d1f814b5760bafa70bac5de7b958#commitcomment-31855812

Fix mousemove listener, we want to consume only our events

---

src/api/abc_timing_callbacks.js

I found convenient to have the measureNumber when handling some sort of manipulation of beat numbers (dealing with visual progress bar, in my specific case).
Though, beatCallback doesn't have a reference to the current measure, and it get a bit weird to recalculate (thinking about repetition and such).
So, my proposal is to invert the order of timingCallback and beatCallback in order to get as soon as possible tune informations  (note, line, measures...) and then eventually beats.

invert beatCallback and timingCallback events

---

src/write/abc_renderer.js
src/write/abc_tempo_element.js
src/write/svg.js

this branch addresses this behavior of Firefox:
https://stackoverflow.com/questions/45184101/error-ns-error-failure-in-firefox-while-use-getbbox
if SVG elements are not visible, getBBox raise an exception.
Basically we fixed enclosing all getBBox occurrences in try/catch.

protect from getBbox exceptions if element not visible

---

src/parse/abc_parse.js
src/parse/abc_parse_directive.js

The draft implements the `%% setbarnb <integer>` pseudo comment.  The following examples demonstrate.
```
const melody = 
'(!tenuto!A2 !tenuto!=B2) (!tenuto!^c2 .B.A) | B=2^f/2B/2 (A^F) F4 |' +
'(=B A2 ^F) .E/2.E/2.A/2.^c/2 e4 |\n' +
'(A2 =B2) (^c2 .B.A) | B=2^f/2B/2 (A^F) F4 |' +
'(=B A2 ^F) .E/2.E/2.A/2.^C/2 E4 |';
const example0 = 'X:2\nL: 1/8\nL: 1/8\nK:F clef=treble\nT:No. 12 excerpt (violin 1)\n%%setbarnb 44\n%%barnumbers 2\n' + melody;
ABCJS.renderAbc('example0', example0);
const example1 = 'X:2\nL: 1/8\nL: 1/8\nK:F clef=treble\nT:No setbarnb\n%%barnumbers 2\n' + melody;
ABCJS.renderAbc('example1', example1);
const example2 = 'X:2\nL: 1/8\nL: 1/8\nK:F clef=treble\nT:No barnumbers\n%%setbarnb 44\n' + melody;
ABCJS.renderAbc('example2', example2);
const example3 = 'X:2\nL: 1/8\nL: …
```

Issue #237: setbarnb measure number

---

src/midi/abc_midi_flattener.js

I try to make a fix for #278 
The codes take the first letter of an explicit bass note to decide its pitch (instead of using the whole text of the bass note to match for pitches, which makes it ignores the bass notes with accidentals). Thereafter, the bass pitch is shifted by the accidental (if any).

Don't ignore chord basses with accidentals when generating midi

---

src/parse/wrap_lines.js

if change script tag in examples\basic.html  as below error raised in src\parse\wrap_lines.js
`
<script type="text/javascript">
var abc = "T: Cooley's\n" +  
"T: SubTitle\n" +
"M: 4/4\n" +
"L: 1/8\n" +
"R: reel\n" +
"K: Emin\n" +
"|:D2|EB{c}BA B2 EB|~B2 AB dBAG|FDAD BDAD|FDAD dAFD|\n" +
"EBBA B2 EB|B2 AB defg|afe^c dBAF|DEFD E2:|\n" +
"|:gf|eB B2 efge|eB B2 gedB|A2 FA DAFA|A2 FA defg|\n" +
"eB B2 eBgB|eB B2 defg|afe^c dBAF|DEFD E2:|";
function load() {
ABCJS.renderAbc("paper", abc, {  
staffwidth: 800,
wrap: { minSpacing: 1.8, maxSpacing: 2.7, preferredMeasuresPerLine: 4 },
});
}
</script>
`

fix wrapLines with several titles

---

src/write/abc_beam_element.js
src/write/abc_renderer.js

This fixes the rendering of downward beamed stems and the beam being drawn short of the stem.

Improve downward stem and beam rendering

---

src/write/abc_abstract_engraver.js
src/write/abc_engraver_controller.js

this adds the ```%%slurgraces``` flag, however i've negated the flag to keep the current default visual.
I'm not sure whether this is the correct default or not.
I'm also unsure whether this would be better to be ```%%slurgraces``` to more closely match the notation section [here](http://abcnotation.com/wiki/abc:standard:v2.1#miscellaneous_directives)

add slurgraces option

---

src/write/selection.js

This PR fixes an issue with selecting notes when the renderer is set to responsive I've only tested this on firefox.
It might be worth checking the svg element actually has these attributes before calculating the scaled values?
Basically what happens is when the renderer is set to responsive the mouse click coords are used which relate to the clicked elements X and Y. What should be used is the rendered svg viewport X and Y as the element and the viewport can be different widths and height.
Also just on a side note i didnt think it was worth posting an issue. I was wondering if youd be open to using something like [standard](https://standardjs.com/) or setting up eslint to format the code base somewhat? I know this can be very opinionated so thought id ask before looking into it?

fix to scale the click coords when paper is set to responsive

---

.gitmodules

I am using my own fork of abcjs with a few modifications to create somewhat of a swiss style drumming notation.
When running a github action to build a project using `npm ci`
with the dependency set to `"abcjs": "git+https://github.com/8633brown/abcjs.git#swiss"`
Npm fails to clone the docs directory as its a submodule.
`npm ERR! fatal: clone of 'git@github.com:paulrosen/abcjs.git' into submodule path '/home/runner/.npm/_cacache/tmp/git-clone-0a77afd7/docs/.vuepress/dist' failed
npm ERR! Failed to clone 'docs/.vuepress/dist'. Retry scheduled`
as far as i can understand, theres no reason for the submodule url to be an ssh type connection and https should suffice and fixes this issue. The only difference being the ssh url actually requires push access to the repo where as the https is read …

use https link over ssh

---

src/write/draw/absolute.js
src/write/draw/voice.js

currently the 6.0.11-beta minified versions are crashing from the separation of the draw functions from the classes.
as far as i can tell the minification is mangling the names and resulting in comparisons of ```object.constructor.name``` to fail as they will never match the correct switch statement. 
using a comparison of the constructor itself should be a better option.

fix mangling of constructor names

---

src/synth/supports-audio.js

As defined will return window.AudioContext which is an anonymous function

Fix supportsAudio() so it always return a bool

---

index.js
src/edit/abc_editarea.js
src/edit/abc_editor.js

This PR seperates the EditArea class from the Editor file and adds it to the public API.
This allows the EditArea object to be called and created externally and redifined instead of completely rewriting the entire object.

seperate editarea from editor to allow function redefinitions

---

src/edit/abc_editor.js

Add the EditArea highlighter to the clickListener now that the editor has access to the renderer params,
This allows any line to be clicked when the `oneSvgPerLine` option is set and still allows the relevant text to be selected,
It currently leaves the previous selected line still highlighted but I'm unsure of the best way to go through each SVG and reset the color yet.
So effectively if there are 4 lines of music one note or element can be selected on each line.

add the highlighter to the clickListener param

---

package.json
types/index.d.ts

As part of [HedgeDoc](https://github.com/codimd/react-client) we wrote these type definitions to use this library, but we think they would have a far better home in this repository.

added types

---

src/parse/abc_parse.js
src/parse/abc_parse_header.js
src/parse/tune-builder.js

main changes...
swap how the line ending is managed by using `string.prototype.replace' with a `/\r\n?/` regex instead of the `parseCommon.gsub' function.
Improve the character replacement for comments after line continuation chars. this allows for unlimited character replacement. this doesnt fix character counts for errors but I'm hoping to get to that eventually.
Initially move all of the page sizing logic to one place. which allows us to remove the `tuneBuilder.cleanUp` arguments.
then move the sizing logic outside of the try catch block this ensures size directives will always be passed to the tune when `header_only` is set, However this now means the tune will always have `formatting.pageWidth` and `formatting.pageHeigth` properties. Although I can't see this as an issue as it just …

parser refactoring

---

src/parse/abc_parse.js
src/parse/abc_parse_music.js
src/parse/abc_tokenizer.js

This improves on how line continuations are parsed.
Currently any line continuation followed by a directive line or (i believe) any heaeder line will not parse the following line correctly.
As the line continuation function in the `Parse.parse` method joins lines ending with a `\` with the next line before any parsing can be done. This causes the individual line parsers to read two lines such as this
`
abc \
%%directive
`
as 
`
abc \%%directive
`
as soon as this line is parsed the directive is parsed as a end of line comment instead.
This can easily be tested with the above example as removing the line continuation will then correctly give an error for the `%%directive`

Line continuations

---

examples/toc.html
examples/tune-instrument-switcher.html
src/synth/load-note.js
src/synth/place-note.js

This fix addresses the issue with race conditions when multiple
instances attempt to load the same note. One instance will
overwrite the resolved AudioBuffer from another instance with the
'pending' string. This fix addresses this by setting an instance
of a Promise instead of strings that represent the status, and
modifies putNote() so that it makes no assumptions about the
status, and instead simply resolves the promise to obtain the
buffer.
An example page is added that provides a demo for dynamic 
instrument (program) switching and toggling between two 
songs.
See #721

Note load race fix

---

docs/visual/tablature.md
src/tablatures/instruments/guitar/guitar-patterns.js

The correct option for renderAbc seems to be `tablature` rather than `tablatures`. This has been updated for the documentation along with a few other issues. For example, the _documented_ default tuning for violin was invalid due to an extra comma.
In addition, the _actual_ default tuning for guitar was invalid due to a missing comma. This has been corrected so that guitar tablature should work under the default settings.

Fix tablature default tuning and documentation

---

types/index.d.ts

I found that some definitions were missing while working on the project using TypeScript and abcjs library.
- The `makeVoicesArray()` is useful, but it is not declared. and recently added `strTranspose` method was also added.
- Added engraver properties.
If I have time later, I plan to explore the source code more deeply, remove the `any` type as much as possible, and define it in more detail.

add missing method and improve type definition

---

src/parse/abc_parse.js
src/parse/abc_parse_key_voice.js
src/parse/abc_parse_music.js

Based on [this section](https://abcnotation.com/wiki/abc:standard:v2.1#clefs_and_transposition) from the ABC music standard (with [clarifications](https://abcnotation.com/wiki/abc:standard:v2.2#the_octave_modifier) from the working draft). This should resolve issue #101.
The `octave` modifier can be set on key and voice fields to directly change the pitch values of ABC code, raising or lowering all pitches by one or more octaves. This applies before any visual or audio transposition and should be equivalent to adding/removing `'` or `,` to note names.
In the example below, all four voices should be equivalent.
```
K: bass
[V:v1]            C,D,E,F,     G,A,B,C     |  % default is octave=0
[V:v2 octave=-1]  CDEF         GABc        |  % read ABC code in Voice 2 down one octave (read c as …
```

Implement 'octave' modifier for K: and V: fields

---

types/index.d.ts

The element can be either a string or an HTMLElement.

Fix SynthObjectController.load type for element

---

src/synth/abc_midi_flattener.js

This is a working PoC of a workaround for #849. The problem is that `%%MIDI drum` is always processed before `M:`. I don't know whether it is intentional. If you like this approach, I can clean it up and even add tests.

Fix metronome with changing meter

---

types/index.d.ts

This is a small fix for the type of the 'format' object in ABCVisualParams.
Currently, TypeScript says that every property of the format object is required. This change makes all the properties of the format object optional, so that it doesn't require every format/font to be given.

Fix type: AbcVisualParams format object

---

types/index.d.ts

I got error`TS 2322`, Property 'tablature' is missing in type 'AbcVisualParams'. So I add `tablature` to `AbcVisualParams`
```ts
const options: AbcVisualParams = {
tablature: [
{
instrument: 'guitar',
},
],
}
```

Add tableture type

---

types/index.d.ts

`strTranspose` expects as its second argument a `TuneObjectArray` as returned by `renderAbc`. However, the typedef incorrectly specified a `TuneObject`. This PR fixes this so that Typescript users won't get thrown off track when trying to pass in the output of `renderAbc`.
(I store the output of `renderAbc` in a variable called `score`. In trying to fix the type errors, I started to pass into `strTranspose` `score[0]` instead of `score`, and spent some non-trivial amount of time trying to figure out why transposition was broken.)

Fix types for `strTranspose`

---

src/write/engraver-controller.js

When using the `scale` and `oneSvgPerLine` parameters of the `renderAbc` function, the distance between the lines is not scaled accordantly.
e.g.: A scale factor of 0.3 results in following rendering:
I would expect that the distance is also scaled down like this:
Using a scalefactor greater then 1 will at some point cut the svg, omitting part of the score
I think the height of the div should be scaled down. The height of the SVG will be changed by the transform but the height of the sourounding div is like it wasn't scaled.
Not sure if I found the right position but it worked for my textcase…

Fix linespacing

---

src/synth/chord-track.js

Doing a transpose, either a %%MIDI transpose or setting a visual transpose at renderABC time sometimes causes octave changes in the backup.
For example, if you take this tune and do a visual transpose of +2, the G chords that get played are still a G, but down an octave.  This change checks the range of the bass after application of the transpose and brings it into the basses[] array range.
X: 1
T: The Kesh
C: Traditional
R: Jig
M: 6/8
L: 1/8
Q: 3/8=120
K: Gmaj
%
% Use an Acoustic Grand Piano sound for the melody:
%%MIDI program 0
%
% Use an Acoustic Grand Piano for the chords:
%%MIDI chordprog 0
%
% Use an Synth Bass sound for the bass:
%%MIDI bassprog 38
%
|:"G"GAG GAB|"D"ABA ABd|"G"edd gdd|"C"edB "D"dBA|
"G"GAG GAB|"D"ABA ABd|"G"edd gdB|"D"AGF "G"G3:|
|:"G"BAB dBd|"C"ege "D"dBA|"G"BAB …

Bring bass note in range if transposed out-of-range

---

src/parse/abc_parse_music.js

If a malformed "@"-style absolute positioned annotation was encountered, the renderer would throw an exception.
This change returns a reasonable chord value that that won't crash the rendering while a malformed absolute positioned annotation is being edited, which is a very common occurrence.
For example lets say user intends to add an annotation:
"@-30,20Hello"
While they are typing this, "@-30Hello" won't crash as it would before with this change in place.  
Once the user finally finished typing the full annotation: 
"@-30,20Hello"
then it will be rendered at the absolute position requested.

Fix for crash on malformed @ positioned annotations
